test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

development:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# To use cloud storage in the future, refer to official Rails guides:
# https://guides.rubyonrails.org/active_storage_overview.html#setup
